day = "Tuesday"
name = "Paul"
food = "Pizza"
days_in_week = 7
one_dozen = 12
smiles_per_mile = 99
pie = 3.14
one_half = .5
number_of_giggawatts = 1.21
is_sunny_today = true
pizza_is_bad = false
music_is_great = true
# variable reassignments
one_dozen = 24
food = "Burger"
name = "Neo"
is_sunny_today = false
